version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
      - './mysqldata:/var/lib/mysql'
      - './script:/script'
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'mysitedb'
       MYSQL_USER: 'cs'
       MYSQL_PASSWORD: 'cs@ubu'
       MYSQL_ROOT_PASSWORD: 'cs@ubu'

  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/mysite
    ports:
      - "80:80"
    depends_on:
      - db
